### ISSUE TITLE
Figure out how to deal with Unicode characters

### ISSUE THREAD

**Issue by mubix** [mubix/twitterfriendsopml#2]
Causes a UnicodeEncodeError:

```
FAILED TO WRITE: User: 6        Feed: https://www.quora.com/profile/Adrián-Lamo/answers/rss
```

**Comment by mubix** [comment]
Stack trace:

```
User: 6 Feed: https://www.quora.com/profile/Adrián-Lamo/answers/rss
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "twitterfeeds.py", line 46, in process_friend
    opmlfile.write(OPML_OUTLINE_FEED % {'title': screenname, 'html_url': url, 'xml_url': feed[0]})
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 131: ordinal not in range(128)
```
